chore: merge

diff --git a/.github/workflows/build-create-release.yml b/.github/workflows/build-create-release.yml
--- a/.github/workflows/build-create-release.yml
+++ b/.github/workflows/build-create-release.yml
@@ -8,10 +8,39 @@ on:
       version:
         description: 'The version for the release'
         required: true
+        default: '0.0.0'
+      draft:
+        description: 'Whether the release should be a draft '
+        required: true
+        default: 'true'
             
 jobs:
+  validate:
+    name: Validates inputs
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+    steps:
+      #validates that the version is a valid semver
+      - name: Validate version
+        id: validate_version
+        run: |
+          if [[ ! ${{ inputs.version }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Invalid version: ${{ inputs.version }}"
+            exit 1
+          fi
+      #validates that the draft is a valid boolean
+      - name: Validate draft
+        id: validate_draft
+        run: |
+          if [[ ! ${{ inputs.draft }} =~ ^(true|false)$ ]]; then
+            echo "Invalid draft: ${{ inputs.draft }}"
+            exit 1
+          fi
+    
   build:
     name: Build packages
+    needs: validate
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
@@ -96,10 +125,15 @@ jobs:
           git checkout -b "release/${{ inputs.version }}"
           git push origin "release/${{ inputs.version }}"
 
-      - name: Create release through github cli and upload assets
+      - name: Create DRAFT release through github cli and upload assets
         env: 
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          gh release create ${{ inputs.version }} --title ${{ inputs.version }} --generate-notes
-          gh release upload ${{ inputs.version }} dist/podshell-macos.zip/podshell-macos.zip --clobber
-          gh release upload ${{ inputs.version }} dist/podshell-windows.zip/podshell-windows.zip --clobber
+        if: ${{ inputs.draft == 'true' }}
+        run: |        
+          gh release create ${{ inputs.version }} --title ${{ inputs.version }} --generate-notes 'dist/podshell-macos.zip/podshell-macos.zip' 'dist/podshell-windows.zip/podshell-windows.zip' --draft
+      - name: Create PUBLISHED release through github cli and upload assets
+        env: 
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        if: ${{ inputs.draft == 'false' }}
+        run: |        
+          gh release create ${{ inputs.version }} --title ${{ inputs.version }} --generate-notes 'dist/podshell-macos.zip/podshell-macos.zip' 'dist/podshell-windows.zip/podshell-windows.zip'  
